/*
 * THIS FILE IS GENERATED BY CLEW - DO NOT EDIT MANUALLY
 *
 * Run `clew spec` to regenerate.
 *
 * @clew homepage: https://ariadne-thread.io
 * @clew connector-type: req-as-code
 * @clew generator-type: java
 * @clew spec-set: ARCH
 */

package clew.traceables.clew;

public enum ArchTraceables {
  ARCH_001_STATE_CHANGE_THROUGH_STORE("ARCH-001"),
  ARCH_002_LAYERING("ARCH-002"),
  ARCH_003_EVERY_PACKAGE_IS_NULL_MARKED("ARCH-003");

  private final String id;

  ArchTraceables(String id) {
    this.id = id;
  }

  public String id() {
    return this.id;
  }
}
