/*
 * THIS FILE IS GENERATED BY CLEW - DO NOT EDIT MANUALLY
 *
 * Run `clew spec` to regenerate.
 *
 * @clew homepage: https://ariadne-thread.io
 * @clew connector-type: req-as-code
 * @clew generator-type: java
 * @clew spec-set: CON
 */

package clew.traceables.clew;

public enum ConTraceables {
  CON_001_NO_DOUBLE_BOOKING("CON-001"),
  CON_002_ATOMIC_CONFIRMATION("CON-002"),
  CON_003_QUOTA_BOUND("CON-003"),
  CON_004_MULTI_ITEM_CONFIRMATION_NEVER_DEADLOCKS("CON-004");

  private final String id;

  ConTraceables(String id) {
    this.id = id;
  }

  public String id() {
    return this.id;
  }
}
