/*
 * THIS FILE IS GENERATED BY CLEW - DO NOT EDIT MANUALLY
 *
 * Run `clew spec` to regenerate.
 *
 * @clew homepage: https://ariadne-thread.io
 * @clew connector-type: req-as-code
 * @clew generator-type: java
 * @clew spec-set: ENT
 */

package clew.traceables.clew;

public enum EntTraceables {
  ENT_001_ITEM("ENT-001"),
  ENT_002_TIME_WINDOW("ENT-002"),
  ENT_003_USER("ENT-003"),
  ENT_004_RESERVATION("ENT-004");

  private final String id;

  EntTraceables(String id) {
    this.id = id;
  }

  public String id() {
    return this.id;
  }
}
