/*
 * THIS FILE IS GENERATED BY CLEW - DO NOT EDIT MANUALLY
 *
 * Run `clew spec` to regenerate.
 *
 * @clew homepage: https://ariadne-thread.io
 * @clew connector-type: req-as-code
 * @clew generator-type: java
 * @clew spec-set: STK
 */

package clew.traceables.clew;

public enum StkTraceables {
  STK_001_NO_DOUBLE_BOOKING("STK-001");

  private final String id;

  StkTraceables(String id) {
    this.id = id;
  }

  public String id() {
    return this.id;
  }
}
