/*
 * THIS FILE IS GENERATED BY CLEW - DO NOT EDIT MANUALLY
 *
 * Run `clew spec` to regenerate.
 *
 * @clew homepage: https://ariadne-thread.io
 * @clew connector-type: req-as-code
 * @clew generator-type: java
 * @clew spec-set: SW
 */

package clew.traceables.clew;

public enum SwTraceables {
  SW_001_CONFIRM_SERVICE("SW-001"),
  SW_002_HOLD_SERVICE("SW-002"),
  SW_003_CANCEL_RELEASE_SERVICE("SW-003"),
  SW_004_QUOTA_SERVICE("SW-004");

  private final String id;

  SwTraceables(String id) {
    this.id = id;
  }

  public String id() {
    return this.id;
  }
}
