/*
 * THIS FILE IS GENERATED BY CLEW - DO NOT EDIT MANUALLY
 *
 * Run `clew spec` to regenerate.
 *
 * @clew homepage: https://ariadne-thread.io
 * @clew connector-type: req-as-code
 * @clew generator-type: java
 * @clew spec-set: SYS
 */

package clew.traceables.clew;

public enum SysTraceables {
  SYS_001_CONFIRM_RESERVATION("SYS-001"),
  SYS_002_AVAILABILITY_QUERY("SYS-002"),
  SYS_003_PLACE_HOLD("SYS-003");

  private final String id;

  SysTraceables(String id) {
    this.id = id;
  }

  public String id() {
    return this.id;
  }
}
